const express = require('express')
const handler = require('../controller/handler')
const upload = require('../middleware/upload')
const route = express.Router()
const passport = require('../middleware/passport')

route.get('/', handler.loginForm)
route.post('/login', passport.authenticate('local', { failureRedirect: '/' }), handler.login)
route.get('/logout', handler.logout)
route.get('/dashboard', passport.checkAuth, handler.home)
route.get('/profile', passport.checkAuth, handler.profile)
route.get('/addAdmin', passport.checkAuth, handler.addAdmin)
route.get('/viewAdmin', passport.checkAuth, handler.viewAdmin)
route.get('/changePassword', passport.checkAuth, handler.changePasswordForm)
route.post('/addNewAdmin', upload, handler.addNewAdmin)
route.get('/Delete/:id', handler.Delete)
route.get('/Edit/:id', handler.Edit)
route.post('/Update', upload, handler.Update)
route.post('/changePassword', handler.changePassword)
route.post('/sendOtp', handler.sendOtp)
route.post('/forgetPass', handler.forgetPass)

module.exports = route